FinalBachelorNeer/Controllers/BlogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DemoBachelorNeer.Controllers
{
    public class BlogController : Controller
    {
        // GET: Blog
        public ActionResult BlogIndex()
        {
            if (Session["users"] != null)
                return View();

            return RedirectToAction("AdvanceSignin", "Signin");
        }
    }
}

FinalBachelorNeer/Controllers/GalleryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DemoBachelorNeer.Controllers
{
    public class GalleryController : Controller
    {
        // GET: Gallery
        public ActionResult GalleryIndex()
        {
            if (Session["users"] != null)
                return View();

            return RedirectToAction("AdvanceSignin", "Signin");
        }

        public ActionResult GalleryDetails()
        {
            if (Session["users"] != null)
                return View();

            return RedirectToAction("AdvanceSignin", "Signin");
        }
    }
}

FinalBachelorNeer/Controllers/PropertiesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DemoBachelorNeer.Controllers
{
    public class PropertiesController : Controller
    {
        // GET: Property


        public ActionResult PropertyIndex()
        {
            if (Session["users"] != null)
                return View();

            return RedirectToAction("AdvanceSignin", "Signin"); 
        }

        public ActionResult PropertyDetails()
        {
            if (Session["users"] != null)
                return View();

            return RedirectToAction("AdvanceSignin", "Signin");
        }
    }
}

FinalBachelorNeer/Controllers/UserprofileController.cs
using FinalBachelorNeer.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FinalBachelorNeer.Controllers
{
    public class UserprofileController : Controller
    {
        bachelorNeerEntities2 db = new bachelorNeerEntities2();
        // GET: Userprofile


        

       
        public ActionResult UserIndex()
        {
            if (Session["users"] != null)
            {
                var viewbag = Session["users"];

                List<Approvedproperty> books = db.Approvedproperties.Where(temp => temp.ap_Email == viewbag).ToList();
                return View(books);
            }
            return RedirectToAction("AdvanceSignin", "Signin");
        }
        [HttpPost]

        public ActionResult UserIndex([Bind(Include = "ap_Name,ap_Email,ap_Number,ap_Type,ap_Proaddress,ap_Thana,ap_Imfile,ap_Rent,ap_Bed,ap_Bath,ap_Kitchen,ap_Belcony,ap_Dinning")] Approvedproperty pd)
        {
            if (ModelState.IsValid)
            {
                db.Approvedproperties.Add(pd);
                db.SaveChanges();
                return RedirectToAction("Congratulation", "AddProperty");

            }
            else
                return RedirectToAction("Error", "ErrorMessage");
        }
    }
}

FinalBachelorNeer/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>BachelorNeer</title>

    <link rel="icon" href="../Design/img/favicon.png" type="image">
    <link href="../Design/css/font-awesome.css" rel="stylesheet">
    <link href="../Design/css/bootstrap.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="../Design/css/slick.css">
    <link rel="stylesheet" type="text/css" href="../Design/css/nouislider.css">
    <link rel="stylesheet" href="../Design/css/jquery.fancybox.css" type="text/css" media="screen" />
    <link id="switcher" href="../Design/css/theme-color/default-theme.css" rel="stylesheet">
    <link href="../Design/css/style.css" rel="stylesheet">

    <link href='https://fonts.googleapis.com/css?family=Vollkorn' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>

</head>
<body>

    <div id="aa-preloader-area">
        <div class="pulse"></div>
    </div>
    <!-- SCROLL TOP BUTTON -->
    <a class="scrollToTop" href="#"><i class="fa fa-angle-double-up"></i></a>
    <!-- END SCROLL TOP BUTTON -->
    <!-- Start header section -->
    <header id="aa-header">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="aa-header-area">
                        <div class="row">
                            <div class="col-md-6 col-sm-6 col-xs-6">
                                <div class="aa-header-left">
                                    <div class="aa-telephone-no">
                                        <span class="fa fa-phone"></span>
                                        +880 1730957466
                                    </div>
                                    <div class="aa-email hidden-xs">
                                        <span class="fa fa-envelope-o"></span> info@bachelorneer.com
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6 col-sm-6 col-xs-6">
                                <div class="aa-header-right">
                                    <a class="aa-register" onclick="location.href='@Url.Action("UserIndex","Userprofile")'">@Session["users"]</a>
                                    <a class="aa-login" onclick="location.href='@Url.Action("BeforeLogin","Home")'">Log Out</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </header>


    <!-- Start menu section -->
    <section id="aa-menu-area">
        <nav class="navbar navbar-default main-navbar" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <!-- FOR MOBILE VIEW COLLAPSED BUTTON -->
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <!-- LOGO -->
                    <!-- Text based logo -->
                    <a class="navbar-brand aa-logo" onclick="location.href='@Url.Action("Index","Home")'"> Bachelor Neer</a>
                    <!-- Image based logo -->
                    <!-- <a class="navbar-brand aa-logo-img" href="index.html"><img src="img/logo.png" alt="logo"></a> -->
                </div>
                <div id="navbar" class="navbar-collapse collapse">
                    <ul id="top-menu" class="nav navbar-nav navbar-right aa-main-nav">
                        <li class="active"><a onclick="location.href='@Url.Action("Index","Home")'">HOME</a></li>
                        <li class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown">PROPERTIES <span class="caret"></span></a>
                            <ul class="dropdown-menu" role="menu">
         
                                <li><a onclick="location.href='@Url.Action("PropertyIndex","Properties")'">PROPERTIES</a></li>
                                <li><a onclick="location.href='@Url.Action("PropertyDetails","Properties")'">PROPERTIES DETAIL</a></li>
                            </ul>
                        </li>
                        <li><a onclick="location.href='@Url.Action("AddPropertyIndex","AddProperty")'">ADD PROPERTY</a></li>
                        <li><a onclick="location.href='@Url.Action("GalleryIndex","Gallery")'">GALLERY</a></li>
                        <li class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" href="blog-archive.html">BLOG <span class="caret"></span></a>
                            <ul class="dropdown-menu" role="menu">
                                <li><a onclick="location.href='@Url.Action("BlogIndex","Blog")'">BLOG</a></li>
                                <li><a href="blog-single.html">BLOG DETAILS</a></li>
                            </ul>
                        </li>
                        <li><a onclick="location.href='@Url.Action("Contact","Home")'">CONTACT</a></li>

                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </nav>
    </section>
    <!-- End menu section -->





    @RenderBody()



    <footer id="aa-footer">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="aa-footer-area">
                        <div class="row">
                            <div class="col-md-3 col-sm-6 col-xs-12">
                                <div class="aa-footer-left">
                                    <p>Designed by <a rel="nofollow" href="https://www.aust.edu/cse">AustCSEStudent</a></p>
                                </div>
                            </div>
                            <div class="col-md-3 col-sm-6 col-xs-12">
                                <div class="aa-footer-middle">
                                    <a href="#"><i class="fa fa-facebook"></i></a>
                                    <a href="#"><i class="fa fa-twitter"></i></a>
                                    <a href="#"><i class="fa fa-google-plus"></i></a>
                                    <a href="#"><i class="fa fa-youtube"></i></a>
                                </div>
                            </div>
                            <div class="col-md-6 col-sm-12 col-xs-12">
                                <div class="aa-footer-right">
                                    <a onclick="location.href='@Url.Action("Index","Home")'">Home</a>
                                    <a href="#">Support</a>
                                    <a href="#">License</a>
                                    <a href="#">FAQ</a>
                                    <a href="#">Privacy & Term</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!-- / Footer -->
    <!-- jQuery library -->


    <script src="../Design/js/jquery.min.js"></script>
    <script src="../Design/js/bootstrap.js"></script>
    <script type="text/javascript" src="../Design/js/slick.js"></script>
    <script type="text/javascript" src="../Design/js/nouislider.js"></script>
    <script type="text/javascript" src="../Design/js/jquery.mixitup.js"></script>
    <script type="text/javascript" src="../Design/js/jquery.fancybox.pack.js"></script>
    <script src="../Design/js/custom.js"></script>

</body>
</html>