FinalBachelorNeer/Controllers/SigninController.cs
using FinalBachelorNeer.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DemoBachelorNeer.Controllers
{
    public class SigninController : Controller
    {
        // GET: Signin

        bachelorNeerEntities2 db = new bachelorNeerEntities2();
        public ActionResult Login()
        {
            return View();
        }
        [HttpPost]

        public ActionResult login(userinfo user)
        {
            

            using (var context = new bachelorNeerEntities2())
            {
                
                bool valid = context.userinfoes.Any(temp => temp.u_Email == user.u_Email && temp.u_Password == user.u_Password);
               
                if (valid)
                {
                    Session["users"] = user.u_Email;
                    
                  
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    ViewBag.errorMessege = "Log in failed";
                    return View();
                }

            }

           
            
        }
        public ActionResult AdvanceSignin()
        {
            return View();
        }
        [HttpPost]

        public ActionResult AdvanceSignin(String Usersss, String Admin, String u_Email, userinfo user)
        {
            //var Admin = Request.Form.GetValues("Admin");
            //var Users = Request.Form.GetValues("User");
            //System.Diagnostics.Debug.WriteLine("user  " + Userss + " admin   " + Admin);

            if (Usersss == null && Admin == null)
            {
                //System.Diagnostics.Debug.WriteLine(Userss+Admin);
                ViewBag.ValidSign = "Select User or Admin!";
            }
            else if(Usersss != null && Admin == null)
            {
                System.Diagnostics.Debug.WriteLine("usernew  "+Usersss+" adminnwe   " + Admin);
                var pdd = db.userinfoes.Where(temp => temp.u_Email.Contains(u_Email)).ToList();
                    if (pdd.Count == 0)
                        ViewBag.ValidSign = "You have no Account! Create account First";

                    else 
                    {

                        using (var context = new bachelorNeerEntities2())
                        {

                            //try
                            //{
                                
                            bool valid = context.userinfoes.Any(temp => temp.u_Email == user.u_Email && temp.u_Password == user.u_Password);
                            //String a = user.u_Email;
                            //String aa = new string(a.ToCharArray().Reverse().ToArray());
                            //aa.Reverse();
                            //String bb = "moc.liamg.reen";
                            //int i = 0, flag = 1;
                            //System.Diagnostics.Debug.WriteLine(aa);
                            //foreach (var temp in bb)
                            //{
                            //    if (temp != aa[i])
                            //    {
                            //        flag = 0;
                            //        break;
                            //    }
                            //    i++;
                            //}
                            if (valid)
                                {
                                    System.Diagnostics.Debug.WriteLine("Successs");
                                     Session["users"] = user.u_Email;
                                     return RedirectToAction("Index", "Home");
                                }
                                else
                                {
                                    ViewBag.ValidSign = "Log in failed";
                                    return View();
                                }
                            
                            //catch (Exception exception)
                            //{

                            //}

                        }
                       
                    }
                
            }
            else
            {
                System.Diagnostics.Debug.WriteLine("user  " + Usersss + " admin   " + Admin);
                var pdd = db.userinfoes.Where(temp => temp.u_Email.Contains(u_Email)).ToList();
                if (pdd.Count == 0)
                    ViewBag.ValidSign = "You have no Account! Create account First";

                else
                {

                    using (var context = new bachelorNeerEntities2())
                    {
                        try
                        {
                            bool valid = context.userinfoes.Any(temp => temp.u_Email == user.u_Email && temp.u_Password == user.u_Password);
                            String a = user.u_Email;
                            String aa=new string(a.ToCharArray().Reverse().ToArray());
                            aa.Reverse();
                            String bb = "moc.liamg.reen";
                            int i = 0,flag=1;
                            //System.Diagnostics.Debug.WriteLine(aa);
                            foreach (var temp in bb)
                            {
                                if (temp != aa[i])
                                {
                                    flag = 0;
                                    break;
                                }
                                i++;
                            }
                            if (valid && flag==1)
                            {
                                
                                
                                
                                Session["admin"] = user.u_Email;
                                return RedirectToAction("Admindashboard", "Admin");
                            }
                            else
                            {
                                ViewBag.ValidSign = "Log in failed";
                                return View();
                            }
                        }
                        catch (Exception exception)
                        {
                            ViewBag.ValidSign = "Error";
                        }

                    }
                    return View();
                }
            }

          return View();
        }
        
    }
}

FinalBachelorNeer/Controllers/SignupController.cs
using FinalBachelorNeer.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FinalBachelorNeer.Controllers
{
    public class SignupController : Controller
    {
        // GET: Signup

        bachelorNeerEntities2 db = new bachelorNeerEntities2();
        public ActionResult UserCreateAccount()
        {
            return View();
        }


        [HttpPost]
        public ActionResult UserCreateAccount([Bind(Include = "u_Name, u_Number, u_Email, u_NID, u_Password")] userinfo user)
        {
            
            if (ModelState.IsValid)
            {

                db.userinfoes.Add(user);
                db.SaveChanges();
                return RedirectToAction("Login", "Signin");

            }
            ViewBag.Error = "Account Create Failed";
            return View();
        }
        public ActionResult AdvanceSignup()
        {

            return View();
        }


        [HttpPost]


        public ActionResult AdvanceSignup(String u_Email, String u_Number, String u_NID, [Bind(Include = "u_Name, u_Number, u_Email, u_NID, u_Password,u_ConPassword")] userinfo user)
        {
            try
            {

                var pd = db.userinfoes.Where(temp => temp.u_Email.Contains(u_Email)).ToList();
                var pd1 = db.userinfoes.Where(temp => temp.u_Number.Contains(u_Number)).ToList();
                var pd2 = db.userinfoes.Where(temp => temp.u_NID.Contains(u_NID)).ToList();

                if (pd.Count > 0)
                {
                    ViewBag.ErrorMessages = "This Email already Used";
                }
                if (pd1.Count > 0)
                {
                    ViewBag.ErrorMessagesss = "This Number already Used";
                }
                if (pd2.Count > 0)
                {
                    ViewBag.ErrorMessagess = "This NID already Used";
                }

                else
                {
                    if (ModelState.IsValid)
                    {

                        db.userinfoes.Add(user);
                        db.SaveChanges();
                        return RedirectToAction("AdvanceSignin", "Signin");
                    }
                    

                }

               
            }
            catch(Exception exception)
            {
                ViewBag.Valid = "Fill Up this form carefully";
                
               // return RedirectToAction("Error", "ErrorMessage");

            }
           return View();
        }
    }
}

FinalBachelorNeer/Views/Signin/AdvanceSignin.cshtml
@{
    Layout = null;
}



<head>

    <link rel="icon" href="../Design/img/favicon.png" type="image">
    <title>BachelorNeer</title>

    <!-- Mobile Specific Metas -->
    <meta name="viewport"
          content="width=device-width, initial-scale=1, maximum-scale=1" />

    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&display=swap"
          rel="stylesheet" />
    <!-- CSS -->
    <link rel="stylesheet" type="text/css" href="../Helper/vendors/styles/core.css" />
    <link rel="stylesheet"
          type="text/css"
          href="../Helper/vendors/styles/icon-font.min.css" />
    <link rel="stylesheet" type="text/css" href="../Helper/vendors/styles/style.css" />


</head>
<body class="login-page">
    <div class="login-header box-shadow">
        <div class="container-fluid d-flex justify-content-between align-items-center">
            <a onclick="location.href='@Url.Action("BeforeLogin","Home")'">
                <div class="navbar-brand aa-logo">
                    <h4>Bachelor Neer</h4>
                </div>
            </a>

            <div class="login-menu">
                <ul>
                    <li><a onclick="location.href='@Url.Action("AdvanceSignup","Signup")'">Register</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="login-wrap d-flex align-items-center flex-wrap justify-content-center">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-md-6 col-lg-7">
                    <img src="../Helper/vendors/images/login-page-img.png" alt="" />
                </div>
                <div class="col-md-6 col-lg-5">
                    <div class="login-box bg-white box-shadow border-radius-10">
                        <div class="login-title">
                            <h2 class="text-center text-primary">Login To BachelorNeer</h2>
                        </div>


                        <form action="/Signin/AdvanceSignin" method="post">
                            <div class="select-role">
                                <div class="btn-group btn-group-toggle" data-toggle="buttons">
                                    <label class="btn active">
                                        <input type="radio" name="Admin" id="admin" value="2" />
                                        <div class="icon">
                                            <img src="../Helper/vendors/images/briefcase.svg"
                                                 class="svg"
                                                 alt="" />
                                        </div>
                                        <span>I'm</span>
                                        Admin
                                    </label>
                                    <label class="btn">
                                        <input type="radio" name="Usersss" id="users" value="1" />
                                        <div class="icon">
                                            <img src="../Helper/vendors/images/person.svg"
                                                 class="svg"
                                                 alt="" />
                                        </div>
                                        <span>I'm</span>
                                        User
                                    </label>
                                </div>
                            </div>
                            <div class="input-group custom">
                                <input type="text" required="required" aria-required="true"
                                       class="form-control form-control-lg"
                                       placeholder="Email" name="u_Email" />
                                <div class="input-group-append custom">
                                    <span class="input-group-text">
                                        <i class="icon-copy dw dw-user1"></i>
                                    </span>
                                </div>
                            </div>
                            <div class="input-group custom">
                                <input type="password" required="required" aria-required="true"
                                       class="form-control form-control-lg"
                                       placeholder="**********" name="u_Password" />
                                <div class="input-group-append custom">
                                    <span class="input-group-text">
                                        <i class="dw dw-padlock1"></i>
                                    </span>
                                </div>
                            </div>

                            <div class="form-group row">
                                <label class="col-sm-4 col-form-label"></label>
                                <div class="col-sm-8">
                                    <h6>@ViewBag.ValidSign</h6>
                                </div>
                            </div>


                            <div class="row pb-30">
                                <div class="col-6">
                                    <div class="custom-control custom-checkbox">
                                        <input type="checkbox"
                                               class="custom-control-input"
                                               id="customCheck1" />
                                        <label class="custom-control-label" for="customCheck1">Remember</label>
                                    </div>
                                </div>
                                <div class="col-6">
                                    <div class="forgot-password">
                                        <a href="forgot-password.html">Forgot Password</a>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-sm-12">
                                    <div class="input-group mb-0">


                                        <input class="btn btn-primary btn-lg btn-block" type="submit" name="Submit" value="Sign In">


                                    </div>
                                </div>
                            </div>
                        </form>
                        <div class="font-16 weight-600 pt-10 pb-10 text-center"
                             data-color="#707373">
                            OR
                        </div>
                        <div class="input-group mb-0">
                            <a class="btn btn-outline-primary btn-lg btn-block"
                               onclick="location.href='@Url.Action("AdvanceSignup","Signup")'">Register To Create Account</a>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>


    <!-- welcome modal end -->
    <!-- js -->
    <script src="../Helper/vendors/scripts/core.js"></script>
    <script src="../Helper/vendors/scripts/script.min.js"></script>
    <script src="../Helper/vendors/scripts/process.js"></script>
    <script src="../Helper/vendors/scripts/layout-settings.js"></script>

</body>

FinalBachelorNeer/Views/Signin/Login.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>BachelorNeer | Home</title>

    <!-- Favicon -->
    <link rel="icon" href="../Design/img/favicon.png">

    <!-- Font awesome -->
    <link href="../Design/css/font-awesome.css" rel="stylesheet">
    <!-- Bootstrap -->
    <link href="../Design/css/bootstrap.css" rel="stylesheet">
    <!-- slick slider -->
    <link rel="stylesheet" type="text/css" href="../Design/css/slick.css">
    <!-- price picker slider -->
    <link rel="stylesheet" type="text/css" href="../Design/css/nouislider.css">
    <!-- Fancybox slider -->
    <link rel="stylesheet" href="../Design/css/jquery.fancybox.css" type="text/css" media="screen" />
    <!-- Theme color -->
    <link id="switcher" href="../Design/css/theme-color/default-theme.css" rel="stylesheet">

    <!-- Main style sheet -->
    <link href="../Design/css/style.css" rel="stylesheet">


    <!-- Google Font -->
    <link href='https://fonts.googleapis.com/css?family=Vollkorn' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>


    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>
    <section id="aa-signin" style="background-image: url(../Design/img/property-header-bg.jpg)">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="aa-signin-area">
                        <div class="aa-signin-form">
                            <div class="aa-signin-form-title">
                                <a class="aa-property-home" onclick="location.href='@Url.Action("Index","Home")'">Bachelor Neer</a>
                                <h4>Sign in to your account</h4>
                            </div>


                            <form class="contactform" action="/Signin/Login" method="post">
                                <div class="aa-single-field">
                                    <label for="email">Email <span class="required">*</span></label>
                                    <input type="email" required="required" aria-required="true" value="" name="u_Email">
                                </div>
                                <div class="aa-single-field">
                                    <label for="password">Password <span class="required">*</span></label>
                                    <input type="password" name="u_Password">
                                </div>
                                <div class="aa-single-field">
                                    <label>
                                        <input type="checkbox">Admin
                                    </label>
                                </div>
                                <div class="aa-single-submit">
                                    <input type="submit" value="Sign in" class="aa-browse-btn" name="Submit"><br />
                                    @ViewBag.errorMessege;
                                    <p>Don't Have A Account Yet? <a onclick="location.href='@Url.Action("UserCreateAccount","Signup")'">CREATE NOW!</a></p>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>




    <script src="../Design/js/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="../Design/js/bootstrap.js"></script>
    <!-- slick slider -->
    <script type="text/javascript" src="../Design/js/slick.js"></script>
    <!-- Price picker slider -->
    <script type="text/javascript" src="../Design/js/nouislider.js"></script>
    <!-- mixit slider -->
    <script type="text/javascript" src="../Design/js/jquery.mixitup.js"></script>
    <!-- Add fancyBox -->
    <script type="text/javascript" src="../Design/js/jquery.fancybox.pack.js"></script>
    <!-- Custom js -->
    <script src="../Design/js/custom.js"></script>

</body>

</html>